sources:
    - name: DemoService
      handler:
        grpc:
          endpoint: localhost:9003
          source:
            load:
              defaults: true
            file: ../demo_service/service_proto/demo_service.proto
serve:
  hostname: localhost 
